[package]
proc-macro = true
name = "uvm_cli_derive"
version = "0.1.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[lib]
name = "uvm_cli_derive"
proc-macro = true

[dependencies]
proc-macro2 = "0.3"
syn = "0.13"
quote = "0.5"
serde_derive_internals = "0.23"
