[package]
name = "uvm_cli"
version = "2.0.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[dependencies]
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
uvm_core = { path = "../uvm_core" }
console = "0.6.1"
