[package]
name = "uvm_core"
version = "2.0.0"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[dependencies]
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
proptest = "0.5.1"
rand = "0.4"
tempdir = "0.3"
