[package]
name = "uvm_core"
version = "2.0.1"
authors = ["Manfred Endres <manfred.endres@tslarusso.de>"]

[dependencies]
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
proptest = "0.8.7"
rand = "0.5"
tempdir = "0.3"
